### ISSUE TITLE
converter.wsdl imports schema from localhost:8080

### ISSUE THREAD

**Issue by sne11ius** [softvision-dev/webpdf-wsclient#3]
Method `getWsdlDocumentLocation` in class `net.webpdf.wsclient.SoapWebService` uses file `wsdl/converter.wsdl` included in the webpdf-wsclient-2.0.1.jar.
The `converter.wsdl` imports a schema from `schemaLocation="http://localhost:8080/webPDF/soap/converter?xsd=1"`. This seems odd, since the webpdf service generally runs on a different server.

So I have two questions

1. Wouldn't it be better to include all xsd files in the jar and import them from there? Maybe using a relative path?
2. Do you happen to know a workaround? I wouldn't really call myself a soap expert, so maybe there's a magic setting to ... just skip this part?

Any suggestions highly appreciated...

**Comment by sne11ius** [comment]
No reaction?

**Comment by christianAppl** [comment]
Hello @sne11ius.
I don´t know whether this issue is still interesting to you, but I wanted to answer it anyway - mostly to apologize.

I have to apologize for this **very** late response to your question!

We seem to have missed the notifications for pending issues on GitHub. (We are used to being contacted via our own ticket system concerning support issues and simply did not check here.)

**Concerning your questions:**
**1. Why are the WSDL files included in the wsclient?**
The webservice API itself did not change much since we included the WSDL files in the project, mostly the parameters of the webPDF webservices did.

It however has always been possible to actively request the WSDLs from the running webPDF server via:
```java
try (SoapSession session = ...))) {
  session.setUseLocalWsdl(false);
  ...
```

Which will cause the wsclient to actively request a matching WSDL from the webPDF server you are attempting to establish a "SoapSession" with.

The default behaviour is avoiding that request, as it is reasonable to expect, that an actively requested WSDL may not differ from the ones included in the wsclient.

**2. Could a public method be created to allow activating this?**
"setUseLocalWsdl" already is a public interface Method of all classes implementing SoapSession.

**3. Could the XSDs be included in the wsclient?**
They actually are and always have been! The WSDLs (even those included in the wsclient project) are used to establish the structure of the WS API itself, they are not used to resolve the parameter schemas.

This also answers your question concerning the schema locations.
You could delete all schema locations from the WSDL files and would not run into issues doing that. The therein contained schema locations are actually ignored entirely. Wsclient is absolutely relying on the included XSDs to create matching stub classes. You can find those in resources/schemas.

Possibly I should remove the schema locations from the WSDL files, to prevent further confusion.


What could be added, is the ability to select another custom source for the SOAP WSDLs, but currently I don´t see much of a benefit in doing so.

I hope I could answer your questions and apologize again for it taking so long.

**Comment by christianAppl** [comment]
I checked my above claims for correctness and whether I could call the converter WS, when "useLocalWsdl" had been set to false. The WS call succeeded.
I assume, that this part of the library did not change much since 2.0.1, I could be wrong about that, as I did not revisit 2.0.1 to check that. (Possibly try updating to 2.0.2?)
